version: '3.8'

services:
  shedulebot:
    build: .
    environment:
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs