DROP TABLE IF EXISTS tasks;
create table IF NOT EXISTS tasks
(
    id          bigint generated by default as identity
        primary key,
    task_id     bigint    not null,
    chat_id     bigint    not null,
    date_time   timestamp not null,
    description text      not null,
    created_at  timestamp not null
);

alter table tasks
    owner to postgres;

CREATE UNIQUE INDEX IF NOT EXISTS tasks_chat_id_task_id_unique
    ON tasks (chat_id, task_id);
