-- auto-generated definition
create table tasks
(
    id          bigint generated by default as identity
        primary key,
    task_id     bigint       not null,
    chat_id     bigint       not null,
    date_time   timestamp    not null,
    description varchar(255) not null,
    created_at  timestamp    not null,
    notified    boolean
);

alter table tasks
    owner to postgres;

create unique index tasks_chat_id_task_id_unique
    on tasks (chat_id, task_id);